cassandra:
        image: 'cassandra:2.2'
        ports:
          - "9042:9042"
          - "9160:9160"
influx:
        image: 'tutum/influxdb'
        ports:
          - "8083:8083"
          - "8086:8086"
