cassandra:
        image: 'cassandra:2.2'
        ports:
          - "9042:9042"
          - "9160:9160"
influx:
        image: 'tutum/influxdb'
        ports:
          - "8083:8083"
          - "8086:8086"
zookeeper:
        image: 'jplock/zookeeper:3.4.6'
        ports:
          - '2181:2181'
kafka:
        image: 'ches/kafka:0.10.0.1'
        links:
          - zookeeper:zookeeper
        ports:
          - "9092:9092"
